name: firebase_auth_repo
description: Dart package which manages the flutter_firebase_auth_bloc domain.
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  google_sign_in: ^6.1.0
  meta: ^1.8.0
  equatable: ^2.0.0
  cache:
    path: ../cache

dev_dependencies:
  firebase_auth_platform_interface: ^7.0.5
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.7